# Cargo-deny config: license and policy checks for this crate.
# See https://embarkstudios.github.io/cargo-deny/

[licenses]
unused-allowed-license = "allow"
confidence-threshold = 0.95
allow = [
    # Currently used across our Rust projects
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "CC0-1.0",
    "ISC",
    "LGPL-2.1-or-later",
    "MIT",
    "MIT-0",
    "OpenSSL",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "Unlicense",
    "Zlib",
    # Common safe licenses in the Rust ecosystem
    "0BSD",
    "Apache-2.0 WITH LLVM-exception",
    "Unicode-DFS-2015",
]
