# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing

__all__ = [
    "PIIDetectorRust",
]

@typing.final
class PIIDetectorRust:
    r"""
    Main PII detector exposed to Python

    # Example (Python)
    ```python
    from pii_filter import PIIDetectorRust

    config = {"detect_ssn": True, "detect_email": True}
    detector = PIIDetectorRust(config)

    text = "My SSN is 123-45-6789 and email is john@example.com"
    detections = detector.detect(text)
    print(detections)  # {"ssn": [...], "email": [...]}

    masked = detector.mask(text, detections)
    print(masked)  # "My SSN is [REDACTED] and email is [REDACTED]"
    ```
    """
    def __new__(cls, config: typing.Any) -> PIIDetectorRust:
        r"""
        Create a new PII detector

        # Arguments
        * `config` - Python dictionary or Pydantic model with configuration

        # Configuration Keys
        * `detect_ssn` (bool): Detect Social Security Numbers
        * `detect_credit_card` (bool): Detect credit card numbers
        * `detect_email` (bool): Detect email addresses
        * `detect_phone` (bool): Detect phone numbers
        * `detect_ip_address` (bool): Detect IP addresses
        * `detect_date_of_birth` (bool): Detect dates of birth
        * `detect_passport` (bool): Detect passport numbers
        * `detect_driver_license` (bool): Detect driver's license numbers
        * `detect_bank_account` (bool): Detect bank account numbers
        * `detect_medical_record` (bool): Detect medical record numbers
        * `detect_aws_keys` (bool): Detect AWS access keys
        * `detect_api_keys` (bool): Detect API keys
        * `default_mask_strategy` (str): "redact", "partial", "hash", "tokenize", "remove"
        * `redaction_text` (str): Text to use for redaction (default: "\[REDACTED\]")
        * `block_on_detection` (bool): Whether to block on detection
        * `whitelist_patterns` (list[str]): Regex patterns to exclude from detection
        """
    def detect(self, text: builtins.str) -> typing.Any:
        r"""
        Detect PII in text

        # Arguments
        * `text` - Text to scan for PII

        # Returns
        Dictionary mapping PII type to list of detections:
        ```python
        {
            "ssn": [
                {"value": "123-45-6789", "start": 10, "end": 21, "mask_strategy": "redact"}
            ],
            "email": [
                {"value": "john@example.com", "start": 35, "end": 51, "mask_strategy": "redact"}
            ]
        }
        ```
        """
    def mask(self, text: builtins.str, detections: typing.Any) -> builtins.str:
        r"""
        Mask detected PII in text

        # Arguments
        * `text` - Original text
        * `detections` - Detection results from detect()

        # Returns
        Masked text with PII replaced
        """
    def process_nested(self, data: typing.Any, path: builtins.str) -> tuple[builtins.bool, typing.Any, typing.Any]:
        r"""
        Process nested data structures (dicts, lists, strings)

        # Arguments
        * `data` - Python object (dict, list, str, or other)
        * `path` - Current path in the structure (for logging)

        # Returns
        Tuple of (modified: bool, new_data: Any, detections: dict)
        """
